### ISSUE TITLE
1.19.2 - Forge 43.1.57 ``Fatal - Failed to Apply Mixins to net.minecraft.world.entity.item.ItemEntity``

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Domaman202/AE2AOFE#11]
Forge Version: 43.1.57
Mod Version: ae2ao-8.1.0-1.19

https://gist.github.com/P3rf3ctXZer0/ab4c3a138a2d19b48a9cd3d50d90f0a1

Issue does not exist with ``
ae2ao-8.0.0-1.19.2``

**Comment by PashkovD** [comment]
I tried to solve your problem in new version 8.1.1. It uploaded to CurseForge. Problem solved?

**Comment by P3rf3ctXZer0** [comment]
I will check give a couple minutes I will close if solved. Please leave this open :)

**Comment by P3rf3ctXZer0** [comment]
Thank you.
