### ISSUE TITLE
1.16.5 - Forge 36.2.39  - Startup Crash ``Mixin apply failed ae2ao.mixins.json:ItemEntityMixin -> net.minecraft.entity.item.ItemEntity`` 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Domaman202/AE2AOFE#12]
ae2ao-8.1.0-1.16

https://gist.github.com/P3rf3ctXZer0/280cd647958b44d116680ac2da8e845c

Like before I will close it when fixed.

Does not crash with 
ae2ao-8.0.0-1.16

**Comment by PashkovD** [comment]
Try newwer version 8.1.1 [CurseForge](https://www.curseforge.com/minecraft/mc-mods/forge-ae2-additional-opportunity/files/4076650)

**Comment by P3rf3ctXZer0** [comment]
Testing now. 

*Update*
- This is for fabric I need fixed for forge

**Comment by PashkovD** [comment]
I made a mistake when specifying the version.  All mods on that page for forge

**Comment by P3rf3ctXZer0** [comment]
yeah but curse won't let me install in with the launcher cause it was marked fabric. Testing now.
