### ISSUE TITLE
update 1.19.2？

### ISSUE THREAD

**Issue by Tatzq** [Domaman202/AE2AOFE#4]
update 1.19.2？

**Comment by Domaman202** [comment]
wip

**Comment by Tatzq** [comment]
What's the degree of completion

**Comment by Domaman202** [comment]
idk - i wait fix ae2 dependencies =)

**Comment by Domaman202** [comment]
40 min. lol
![image](https://user-images.githubusercontent.com/51743763/188424817-32fb6140-11e8-4d53-93d0-7d20e620e3fb.png)

**Comment by Tatzq** [comment]
Thank you for your hard work

**Comment by Domaman202** [comment]
This not hard. Thanks for using the mod! ^^
![image](https://user-images.githubusercontent.com/51743763/188437394-1913750d-07ec-48a3-a9ab-5d9e7f23ef0e.png)
