### ISSUE TITLE
Failure message: Mod ae2ao only supports ae2 10 or above, and below 11 Currently, ae2 is 11.6.4

### ISSUE THREAD

**Issue by j4rw15** [Domaman202/AE2AOFE#9]
Mod File: /C:/Minecraft/Servers/MyModpackServer/mods/ae2ao-8.0.0-1.18.jar
	Failure message: Mod ae2ao only supports ae2 10 or above, and below 11
		Currently, ae2 is 11.6.4
	Mod Version: 8.0.0
	Mod Issue URL: NOT PROVIDED
	Exception message: MISSING EXCEPTION MESSAGE

**Comment by PashkovD** [comment]
Use version 8.1
